---
# You must restart the Rack server after changing either of these values
# because they are cached at startup.
#
:unattended: true
:login: true
:require_ssl: false
:locations_enabled: false
:organizations_enabled: false
:support_jsonp: false
:mark_translated: false
:admin_email: noreply@foreman.org

:require_ssl_smart_proxies: false
:restrict_registered_smart_proxies: false
:foreman_url: http://haproxy
:unattended_url: http://haproxy
:remote_execution_fallback_proxy: true
:loggers:
  :app:
    :enabled: true
  :ldap:
    :enabled: false
  :permissions:
    :enabled: false
  :sql:
    :enabled: true
:memcache:
  :hosts:
    - memcache
  :options:
    :namespace: foreman
    :expires_in: 86400
    :compress: true
